### ISSUE TITLE
Leapfrog algorithm. Exercise 1.2

### ISSUE THREAD

**Issue by isavoj** [softmatterlab/SOCS#28]
Exercise 1.2
Leapfrog algorithm is wrong in example on github and in book (?) 

Works with: 

  v[i + 1] = v[i] - k/m*x[i]*dt
  x[i+1] = x[i] + v[i+1]*dt

**Comment by acallegar** [comment]
So, to emphasize:

1) in the leapfrog, you have to add the "intermediate position" variable (which I called xh ) indicating the position at half time step from the initial one

2) that position (xh) is used to calculate the force

3) with the force you calculate the velocity one time step after

4) with the new velocity and the intermediate position you calculate x[n+1]

The equations to implement are the one in the book.

I gave the implementation for the leapfrog, harmonic oscillator. Also, please make the same changes for the damped oscillator.
