### ISSUE TITLE
Sign error. Exercise 1.5

### ISSUE THREAD

**Issue by isavoj** [softmatterlab/SOCS#29]
In exercise 1.5, 
I believe there is a sign error on gamma γ in the case of overdamped oscillations.

**Comment by acallegar** [comment]
I checked the code:
(https://github.com/softmatterlab/SOCS/blob/main/Chapter_01_Molecular_Dynamics/Damped_oscillator.ipynb)

I think there is no problem in the sign of gamma (in the implementation).

Is the problem in the code implementation or in the formulas in the book?

Thanks in advance,

**Comment by acallegar** [comment]
Issue has been solved.
