### ISSUE TITLE
Figure 4.6e is incorrect

### ISSUE THREAD

**Issue by JosephLofving** [softmatterlab/SOCS#31]
Figure 4.6e is just a copy of figure 4.6g/i:
![2021-11-12-09:52:12](https://user-images.githubusercontent.com/55035390/141438804-6696e21d-9cf6-429f-b2af-7d7d7d240ddd.png)
It should look something like this:
![4d2git](https://user-images.githubusercontent.com/55035390/141440025-bc64138e-b1e4-453e-9b7e-6910f4fddbcd.png)

**Comment by acallegar** [comment]
Thanks for spotting the mistake. 
We will correct Figure 4.6e
