### ISSUE TITLE
Incorrect probability of node degree in eq. 12.1

### ISSUE THREAD

**Issue by JosephLofving** [softmatterlab/SOCS#32]
![2021-11-19-16:51:02](https://user-images.githubusercontent.com/55035390/142651689-f751d29c-8fe3-4f12-ac23-a415cf7403ab.png)
The first factor shouldn't be a division, but the binomial coefficient n-1 choose k.

**Comment by acallegar** [comment]
Thanks for spotting the error. We will correct the formula.
