### ISSUE TITLE
Update readme files

### ISSUE THREAD

**Issue by giovannivolpe** [softmatterlab/SOCS#34]
- [x] main
- [x] ch 1
- [x] ch 2
- [x] ch 3
- [x] ch 4
- [x] ch 5
- [x] ch 6
- [ ] ch 7
- [ ] ch 8
- [x] ch 9
- [x] ch 10
- [x] ch 11
- [x] ch 12
- [ ] ch 13
- [ ] ch 14
- [ ] ch 15
- [ ] ch 16

**Comment by acallegar** [comment]
Hi, I updated the README.md (please view related pull requests).

**Comment by acallegar** [comment]
I have fixed the Readme of Chapter 7, 8, 13, 14, 15, 16.
I corrected a typo in the readme of chapter 4.
